[MFLOG|0|2022-10-31T14:42:44.938482Z|runtime|170b8d15-1ee2-48ae-86b0-f6e58747f942]<flow SVMFlow step train_model[1] (input: 1)> failed:
[MFLOG|0|2022-10-31T14:42:44.943278Z|runtime|804b7ae7-ee07-49d3-82f7-8ce163fce01f]    Internal error
[MFLOG|0|2022-10-31T14:42:44.944772Z|runtime|3b605b1d-1abf-4476-9c31-e6f715f73970]Traceback (most recent call last):
[MFLOG|0|2022-10-31T14:42:45.103891Z|runtime|363bd77d-26e0-40cd-8179-77e827b43057][KILLED BY ORCHESTRATOR]
[MFLOG|0|2022-10-31T14:42:45.104025Z|runtime|d7931adf-eee2-4b4d-a8a3-d7c2fb5a910c]  File "/Users/qinyixin/opt/anaconda3/lib/python3.9/site-packages/metaflow/cli.py", line 1110, in main
[MFLOG|0|2022-10-31T14:42:45.104061Z|runtime|837657dc-5a67-487a-b3d2-0c3ba0898619]    start(auto_envvar_prefix="METAFLOW", obj=state)
[MFLOG|0|2022-10-31T14:42:45.104089Z|runtime|5aa55af3-4da4-4891-a401-3a90bed747cf]  File "/Users/qinyixin/opt/anaconda3/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
[MFLOG|0|2022-10-31T14:42:45.104115Z|runtime|8f038868-0c5b-4cbc-8de3-3089f2f77daa]    return self.main(args, kwargs)
[MFLOG|0|2022-10-31T14:42:45.104139Z|runtime|3a26168e-8351-4b65-aafd-419636031211]  File "/Users/qinyixin/opt/anaconda3/lib/python3.9/site-packages/click/core.py", line 1053, in main
[MFLOG|0|2022-10-31T14:42:45.104160Z|runtime|857b5e39-d480-475c-9fc5-95cf0eebf3e5]    rv = self.invoke(ctx)
[MFLOG|0|2022-10-31T14:42:45.104182Z|runtime|a672e04f-2472-4ec3-a74a-b3aca31a3e45]  File "/Users/qinyixin/opt/anaconda3/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
[MFLOG|0|2022-10-31T14:42:45.104206Z|runtime|e89cfe2e-9529-408e-b05e-81a75cd1bfe3]    return _process_result(sub_ctx.command.invoke(sub_ctx))
[MFLOG|0|2022-10-31T14:42:45.104228Z|runtime|b5dbd26b-a98e-43e1-b06c-65a1641327fd]  File "/Users/qinyixin/opt/anaconda3/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
[MFLOG|0|2022-10-31T14:42:45.104252Z|runtime|eebaa8b8-e2e7-4764-9441-05b91fb6cbaa]    return ctx.invoke(self.callback, ctx.params)
[MFLOG|0|2022-10-31T14:42:45.104274Z|runtime|97a5cede-a87a-46d4-9409-f3930dee5198]  File "/Users/qinyixin/opt/anaconda3/lib/python3.9/site-packages/click/core.py", line 754, in invoke
[MFLOG|0|2022-10-31T14:42:45.104295Z|runtime|e3311b22-9ba7-4a9f-99ba-ed8a34b042fc]    return __callback(args, kwargs)
[MFLOG|0|2022-10-31T14:42:45.104317Z|runtime|5528ad85-2479-42df-8f99-ab51491703e2]  File "/Users/qinyixin/opt/anaconda3/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
[MFLOG|0|2022-10-31T14:42:45.104341Z|runtime|d74ef67f-4d9a-4f39-a25d-8c8e888331d3]    return f(get_current_context(), args, kwargs)
[MFLOG|0|2022-10-31T14:42:45.104362Z|runtime|6ef03d1d-7eaa-41b0-b883-e4ff29d8354e]  File "/Users/qinyixin/opt/anaconda3/lib/python3.9/site-packages/metaflow/cli.py", line 544, in step
[MFLOG|0|2022-10-31T14:42:45.104384Z|runtime|2ce943b8-4419-4742-8f23-9e3a20744c42]    task.run_step(
[MFLOG|0|2022-10-31T14:42:45.104405Z|runtime|af23c011-9ac5-4221-9086-7abf5cf0bb02]  File "/Users/qinyixin/opt/anaconda3/lib/python3.9/site-packages/metaflow/task.py", line 547, in run_step
[MFLOG|0|2022-10-31T14:42:45.104427Z|runtime|360b8408-6d64-4be4-a8cc-66ccf1f6d213]    self._exec_step_function(step_func)
[MFLOG|0|2022-10-31T14:42:45.104448Z|runtime|a223ce16-481a-45bf-bba8-1c05263bbcfd]  File "/Users/qinyixin/opt/anaconda3/lib/python3.9/site-packages/metaflow/task.py", line 53, in _exec_step_function
[MFLOG|0|2022-10-31T14:42:45.104470Z|runtime|bd574dbd-d78e-4b57-91ee-695929e6ec42]    step_function()
[MFLOG|0|2022-10-31T14:42:45.104491Z|runtime|9c8e8d20-4c3e-4d45-89bc-4d4e3da0bfd2]  File "/Users/qinyixin/Desktop/7773_assignement/flow.py", line 95, in train_model
[MFLOG|0|2022-10-31T14:42:45.104513Z|runtime|009d5d29-e8ee-4b67-a996-cbd8fcfeca1a]    self.scores = cross_val_score(reg, self.Xs, self.ys, cv=6)
[MFLOG|0|2022-10-31T14:42:45.104536Z|runtime|1adb7cd0-1d5c-4f49-9565-705b4f35a8e5]  File "/Users/qinyixin/opt/anaconda3/lib/python3.9/site-packages/metaflow/flowspec.py", line 223, in __getattr__
[MFLOG|0|2022-10-31T14:42:45.104558Z|runtime|018e25a1-5305-43c0-8c76-670111bdbc43]    raise AttributeError("Flow %s has no attribute '%s'" % (self.name, name))
[MFLOG|0|2022-10-31T14:42:45.104580Z|runtime|0f13c41c-2a38-4f04-b373-cc66eb3d9236]AttributeError: Flow SVMFlow has no attribute 'ys'
[MFLOG|0|2022-10-31T14:42:45.104602Z|runtime|7fab3343-2035-4b81-9db5-94374850a5ce]
[MFLOG|0|2022-10-31T14:42:45.104750Z|runtime|5acf9a89-86c9-4209-962d-f8ee9f93d0ca]Task failed.